# Generated by Django 6.0.3 on 2026-03-15 11:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("upload_path", models.CharField(max_length=1000)),
                ("output_path", models.CharField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("current_stage", models.CharField(blank=True, max_length=200)),
                ("error_message", models.TextField(blank=True)),
                ("processing_log", models.JSONField(blank=True, default=dict)),
                ("file_size_mb", models.FloatField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("elapsed_seconds", models.FloatField(blank=True, null=True)),
                ("methods_used", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
